language: python
python:
  - "2.7"
before_install:
  - git submodule update --init --recursive
install:
  - "pip install -r requirements.txt"
script:
 - cd bin
 - python generate.py --write-fhir ../generated-data
 - cd ../custom-data
 - ./generate.sh 
